package-lock.json
package.json

Fix the base dependencies issue
- Added `@types/node` package
- Regenerated `package-lock.json`

Fix base dependecies issue

---

README.md

Updated README.md to warn contributors of the use of TailwindCSS going forward.
updated README.md
Should close #64

[documentation] Inform contributors of the use of TailwindCSS

---

src/App.tsx
src/components/molecules/UserIDForm.tsx
src/components/molecules/UserNameForm.tsx
src/helpers/textUtils.ts
src/hooks/useUserNameForm.ts
src/i18n/i18n.constants.ts
src/i18n/i18n.translations.ts
src/i18n/pages/registrationName.ts
src/pages/EditNewPassword.tsx
src/pages/RegistrationName.tsx
src/pages/RegistrationUserID.tsx

Create the screens for [Name Registration (1st step)](https://www.figma.com/file/eaAfUatNrDWpFPbkCsLMYG/Frontend-contribution---Onboarding-process?node-id=1%3A1633)
[Issue #4 ](https://github.com/TheTributeCommunity/fesbal-frontend/issues/4)
- Add new page for registration step for i18n lib
- Create registration form
- Create registration page (in the same structure as user ID registration page) - This should be better if refactored to be a multi-step form, and not a multi-page one. But for the future, I believe.
[Issue #4 ](https://github.com/TheTributeCommunity/fesbal-frontend/issues/4)

Feature 4/create name registration - 1st step

---

src/App.tsx
src/components/atom/AppPopupAlert.tsx
src/components/icons/PlusAddIcon.tsx
src/helpers/index.ts
src/helpers/widthSwalCalculation.ts
src/hooks/useLoginPasswordRecovery.ts
src/hooks/useMenuDeleteAccount.ts
src/hooks/useProfileEditEmail.ts
src/hooks/useProfileEditNewPassword.ts
src/hooks/useRegisterFamilyMembers.ts
src/i18n/i18n.constants.ts
src/i18n/i18n.translations.ts
src/i18n/pages/registerFamilyMembers.ts
src/pages/RegisterFamilyMembers.tsx
src/pages/RegisterReferral.tsx
src/styles/index.scss
src/styles/variables.scss

This pull request adds a new feature for the registration process, the "RegisterFamilyMembers" page, which allows users to add family members to their account in order to update the number of food items received. They also have a link to continue without add family members.
- Add a new page, "RegisterFamilyMembers," to the Router.
- Add i18n text for the "RegisterFamilyMembers" page.
- Add a hook to the "RegisterFamilyMembers" page.
- Disable the "Continuar" button until at least one family member is added.
- RegisterFamilyMembers:
- Issue #21  
This branch was created from the branch _feature-48-50/access-current-referral-from-and-upload-a-new-one_
URL: https://github.com/TheTributeCommunity/fesbal-frontend/pull/56

Feature 18/user adds new family members to his her account

---

.github/workflows/deploy.yml

This PR adds GitHub Actions' workflow to deploy automatically to AWS on main commit

Add GitHub Actions' workflow to deploy automatically to AWS on main commit

---

src/pages/PickupHistoryPage.tsx
src/types/ButtonProps.ts

fixing deploy errors

---

.github/workflows/deploy.yml

fixing auto-trigger

---

CONTRIBUTING.md

Added refactor branch template
Updated `CONTRIBUTING.md` with refactor branch template

Add refactor branch example

---

.eslintrc.json
.gitignore
.vscode/extensions.json
README.md
package-lock.json
package.json

Linter added. Rules are more or less what we were doing already. Rules can be modified in the future.
- Added eslint package
- Added eslint config
- Added recommended VSCode extensions file
- Modified README to communicate change, included instructions on how to set up VSCode to lint on save

added linter

---

src/hooks/useEntityLoginPasswordRecovery.ts

API call to method which does not yet exist is blocking the build process.
Commented out API call to backend which does not yet exist.

fix: comment out line breaking deployment, unimplemented back call

---

src/pages/WelcomeScreen.tsx

Splash screen shows then transitions into login/register page
- Added splash transition after 1 second
Should close #113

[Screen 00 - Issue 113]

---

src/pages/EntityLogin.tsx

Fix page passing wrong parameter to AppWrapper.
Remove wrong prop to AppWrapper

FIX: fixed wrong prop to appwrapper

---

src/App.tsx
src/pages/EntityProfile.tsx

This fixes some build errors introduced by the conflict resolution in a previous PR. **Note to self: pull after resolving conflicts and build locally to check for errors**.
- Removed startWithWhite property (nice but unnecessary)
- Some formatting details

FIX: fixed build errors from bad conflict resolution

---

package-lock.json
package.json

bump security versions

---

src/components/atom/RegisterPersonalDataItem.tsx
src/components/molecules/AppReferralForm.tsx
src/components/molecules/ReferralFileUploaded.tsx
src/hooks/useUploadReferral.ts
src/i18n/pages/registerReferral.ts
src/i18n/pages/registerRequestSent.ts
src/models/referral-sheet-upload-url.ts
src/pages/RegisterRequestSent.tsx
src/services/recipient-user-service.ts

Fix referral sheet upload and request sent screens
- Referral sheets are correctly uploaded
- Request sent screen now uses real data
- Other small fixes like overflowing text

referral sheet upload fixes

---

src/components/atom/Spinner.tsx

Changed spinner design, as requested from the design team
- Spinner updated with new design

Spinner updated

---

index.html

Default font color set to midnight blue
- body default font color set to midnight blue

[F-41] fix default font color

---

src/hooks/useRegisterReferralSendDate.ts
src/hooks/useUploadReferral.ts
src/models/registration-request.ts
src/services/registration-request-service.ts

Integrate the send registration request operation after set the social service appointment or referral sheet upload

Feat Send registration request

---

src/pages/RegisterRequestSent.tsx

Font weights, layout and spacing fixed in request sent
- Font weights changed
- Layout changed
- Spacing changes

F-46: font weights and spacing fixed in request sent screen

---

src/components/molecules/AppWrapper.tsx
src/components/molecules/BurgerMenu.tsx
src/pages/ProfileScreen.tsx
src/pages/RecipientLandingScreen.tsx
src/pages/Welcome.tsx

demo fixes

---

src/components/atom/FamilyMemberCard.tsx
src/helpers/getFamilyUnitAges.ts
src/hooks/useRegisterFamilyMembers.ts
src/models/recipient-user.ts
src/pages/RegisterRequestSent.tsx
src/services/recipient-user-service.ts

Check namings to sync with backend endpoints
- Changed RecipientUser to Recipient
- Sync graphql operations to backend

refactor: check namings to sync with backend

---

src/App.tsx

Entity login routes were protected before, but that meant they were inaccessible without first logging in, not they are unprotected so users can log in.
- Entity login routes unprotected

entity login routes unprotected

---

src/hooks/useEntityInfo.ts
src/models/entity.ts
src/pages/EntityHome.tsx
src/services/entity-service.ts

Connect entity service with backend to show entity name in home screen
- Created Entity model
- Created useEntityInfo
- Created EntityService
- Changes entity home to show entity name

FESBAL-49 - Show entity name in home screen

---

src/models/entity.ts
src/pages/EntityProfile.tsx
src/services/entity-service.ts

FESBAL-50 Connect entity profile with backend
- updated entity model with all the necessary field
- updated entityProfile page to get info form backend
- updated getEntityById to retrieve all the fields

FESBAL-50 Connect entity profile with backend

---

src/App.tsx
src/hooks/useRegisterFamilyMembers.ts
src/services/refresh-token-service.ts
src/services/relative-service.ts

Tokens were not getting refreshed before, now they are refreshed, and the subscription used for relatives does not produce duplication of data in some situations.
-Tokens get refreshed by calling a function which checks expiry, every time the window is focused, or whenever a certain timer finishes, which is set based on token expiry.

refresh tokens fixed; subscriptions work better now

---

src/pages/MenuReferralUpload.tsx
src/pages/RegisterReferral.tsx

Burger menu not shown in referral sheet upload screens.
- Burger menu hidden in referral upload screens
- [n/a ] Updated documentation accordingly

[FESBAL-45] burger not shown in referral upload screen

---

src/components/atom/FamilyMemberCard.tsx
src/hooks/useRegisterFamilyMembers.ts
src/i18n/pages/registerFamilyMembers.ts
src/pages/AddFamilyMember.tsx
src/pages/ProfileScreen.tsx
src/pages/RegisterFamilyMembers.tsx

Register family members popup now properly shows up, copy updated, profile family members list width now fixed for other widths other than mobile.
- Register family members popup now properly shows up
- Copy updated
- Profile family members list width now fixed for widths other than mobile.
- [n/a ] Updated documentation accordingly

[FESBAL-43] Register relatives popup fixed, copy edited, profile width issues fixed

---

src/hooks/useRegisterEmailForm.ts
src/i18n/pages/registerEmail.ts
src/pages/RegisterEmail.tsx

Email registration form should allow an empty email, as it is optional. Confirmation dialog skipped, text changed to reflect optionality.
- Updated copy to reflect optionality
- Confirmation dialog removed
- Email now optional during registration

[FESBAL-58] email registration fixes

---

src/components/molecules/BurgerMenu.tsx
src/helpers/getCurrentRoute.ts

Burger menu styling updated, current route highlighted.
- burger menu icon alignment on right rather than left
- burger menu refactored
- current route highlighted on burger menu
screenshot:

[FESBAL-47] burger menu fixes added

---

src/components/molecules/BurgerMenu.tsx
src/enums/external-links.ts
src/pages/RegisterLegal.tsx

Added new links and refactored external links usage.
- Added a new external link (placeholder link for actual T&Cs link)
- Refactored how we use external links

[FESBAL-71] added external links, refactored external links

---

src/components/molecules/AppMessageDialog.tsx

Message dialogs looked squashed horizontally in viewports bigger than mobile.
- fixed viewport issues for message dialogs

Fixed message dialog viewport issues

---

package-lock.json
package.json
src/helpers/dateHelper.ts
src/hooks/useRegisterIDForm.ts
src/pages/AddFamilyMember.tsx

ID only mandatory if relative is 18 years of age or older, input characters limited to alphanumeric characters
- ID only mandatory if relative is 18 years of age or older
- input characters limited to alphanumeric characters
- Added new dependency `moment.js`
**Do an npm install to get the new dependency!**

[FESBAL-51] ID optional depending on age, input characters limited

---

src/components/atom/HistoryCard.tsx
src/pages/EntityDeliveryHistory.tsx
src/pages/EntityProfile.tsx
src/services/PickupService.ts
src/types/FoodPicking.ts
src/types/Pickup.ts

feat: checkpoint

---

src/services/entity-service.ts
src/types/Entity.ts

remove entity nextDelivery

---

src/components/atom/LoginCard.tsx
src/components/molecules/LoginList.tsx

Updated welcome screen UI.
- Removed background logo
- Updated account creation button

FESBAL-110: updated welcome screen

---

src/i18n/pages/registerReferral.ts
src/pages/RegisterReferral.tsx

Referral upload modal updated.
- Copy updated
- Navigation updated

FESBAL-119: updated copy and navigation for referral upload success

---

src/components/atom/FamilyMemberCard.tsx
src/pages/ProfileScreen.tsx
src/pages/RegisterFamilyMembers.tsx
src/types/ButtonProps.ts

few more changes

---

src/components/molecules/AppMessageDialog.tsx

Dialogs centered on the screen.
- Dialogs are now centered on the screen, instead of at the bottom

FESBAL-129: dialogs centered

---

src/components/molecules/AppReferralForm.tsx
src/i18n/pages/registerReferral.ts
src/pages/MenuReferralUpload.tsx
src/pages/RegisterReferral.tsx

Referral form upload copy updated and other details
- Copy updated
- Page header updated
- Layout spaced out

FESBAL-113: referral form upload copy updated and other details

---

src/i18n/pages/loginValidatePhone.ts
src/i18n/pages/validatePhone.ts
src/pages/LoginValidatePhone.tsx
src/pages/ValidatePhone.tsx

Copy updates and modal changes.
- Copy updates
- Modal for successful validation of phone does not appear when logging in, only when registering.

FESBAL-111: copy updates and modal changes

---

src/components/molecules/AppReferralForm.tsx
src/graphql/recipient-queries.ts
src/hooks/useEntities.ts
src/hooks/useUploadReferral.ts
src/models/entity.ts
src/models/referral-sheet-upload-input.ts
src/models/referral-sheet-upload-url.ts
src/pages/MenuReferralUpload.tsx
src/pages/RegisterReferral.tsx
src/services/entity-service.ts
src/services/recipient-user-service.ts
src/types/Option.ts

Referral upload page now lists entities, dropdown rework and other UI adjustments.
- Referral upload screens now show entities, and pass entity and date to the backend when uploading the referral sheet
- Dropdown component modified a bit
- Other UI changes in the page to everything fits in most mobile screen heights

FESBAL-75: referral entities list and other UI changes

---

src/components/atom/SearchInput.tsx

Small restyle to the recipient search component.
- Small style changes to the recipient search component

FESBAL-128: recipient search restyle
